import esbuild from "esbuild";
import process from "process";

const production = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Codigo-fonte em: main.ts e src/
*/`;

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["main.ts"],
    bundle: true,
    // Modulos fornecidos pelo ambiente do Obsidian / Electron — nao devem ser empacotados.
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
    ],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: production ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: production,
});

if (production) {
    await context.rebuild();
    await context.dispose();
    process.exit(0);
} else {
    await context.watch();
}
